### PR TITLE
Check a few more prefixes for the builtin_mod test

### LINKED ISSUE #93: Pickling Error: can't pickle <class 'PyCapsule'>: it's not found as builtins.PyCapsule
I have this problem with pickling data with dill. The problem only occurs on python 3.4. My code works with python 3.3 and python 2.7.

### PR DESCRIPTION
**Pull request by matsjoyce**
This should fix #93, as this consults all the prefixes in the docs, plus `real_prefix`, which is from virtualenv. Could @itdxer test this? And should I be worried that this is my fifth commit on this small bit of code?

### CODE REVIEW

**Comment by mmckerns** [comment]
@matsjoyce: worried… probably, yes.  It's usually a sign of patching too late in the workflow as opposed to stemming it at the right spot.  However, sometimes doing so is a much harder fix. I'll wait and see if we get confirmation from @itdxer.

**Comment by itdxer** [comment]
Thanks, this patch works fine for me!

**Comment by mmckerns** [comment]
@matsjoyce:  I'd pull this, but it's not up-to-date with the current version of `dill.dill` in master.  I can manually merge in the changes, or you can update.  It's up to you.  Once I have a merged file, I'll check for test failure.  Then it's in.

**Comment by mmckerns** [comment]
A quick manual merge of the changes you made confirms all tests pass.  If you update `dill.py` in your PR, I'll merge it right in.

**Comment by matsjoyce** [comment]
Whoops, that's what I get for blindly stashing to a branch I didn't update. Sorry, fixed.

**Pull request merged**
