### PR TITLE
Minor type fix

### PR DESCRIPTION
**Pull request by victorcwai**
Fix type of argument `module` in `load_module` in `dill/session.py`

### CODE REVIEW

**Comment by leogama** [comment]
This is interesting. If I remember right, I had at some point set the type hint to `Optional[...]`, but then I noted that, even if it wasn't explicitly marked in this way but had a default value of `None`, the generated documentation correctly annotated the argument as optional. Then I removed the `Optional`.

Does this affect type checking with some tool, e.g. `mypy`?

**Comment by victorcwai** [comment]
Yes, that affects type checking with `pyre`. But it seems that in `mypy`, initializing arguments to `None` is passable (under non-strict setting).

**Comment by mmckerns** [comment]
@victorcwai: Do you experience the same issue with `dump_module`: https://github.com/uqfoundation/dill/blob/f196e3c9cbbba3326064c09760f7129df7f3de4d/dill/session.py#L132
and in `load_module_asdict`:
https://github.com/uqfoundation/dill/blob/f196e3c9cbbba3326064c09760f7129df7f3de4d/dill/session.py#L494
?

**Review by mmckerns — COMMENTED** [review]
Please respond to the question from the reviewer.  Otherwise LGTM.

**Comment by victorcwai** [comment]
Same issue with dump_module. But no problems with load_module_asdict.

**Comment by mmckerns** [comment]
Ok, makes sense. Thanks.

**Comment by victorcwai** [comment]
Shall we merge this? :)

**Review by mmckerns — CHANGES_REQUESTED** [review]
Please make the similar change to https://github.com/uqfoundation/dill/blob/f196e3c9cbbba3326064c09760f7129df7f3de4d/dill/session.py#L132. Otherwise LGTM.

**Comment by mmckerns** [comment]
I just went ahead and made the changes requested, then merged.

**Pull request merged**
