### PR TITLE
Python 3 Metaclasses [Support ABC and Enums - Part 1]

### PR DESCRIPTION
**Pull request by anivegesana**
This PR is part 1 of the broken down version of #450. It extends support of metaclass pickling to features added in Python 3.0, 3.6, and 3.7 (https://peps.python.org/pep-3115/, https://peps.python.org/pep-0487/, https://peps.python.org/pep-0560/).

### CODE REVIEW

**Comment by anivegesana** [comment]
I think the coverage issue can be ignored. The coverage passes in #450 and it is failing here because the ABC and enum tests are not in this PR.

**Comment by anivegesana** [comment]
@mmckerns Should I add test cases that test this feature without using enums or ABCs, or is this feature ready for review?

**Comment by mmckerns** [comment]
Please always request a review when you feel a PR is ready to be reviewed.  Otherwise, it's hard to know what the state of the PR is.   You should always add tests cases, unless the change is trivial.

**Comment by anivegesana** [comment]
I think that I don't have the permissions to request a review. I am just marking PRs that aren't ready for review as drafts. Will create test cases for these features to improve coverage.

**Comment by anivegesana** [comment]
@mmckerns It should be ready for review now.

**Review by mmckerns — APPROVED** [review]
lgtm

**Comment by anivegesana** [comment]
The size of this PR seems to be more manageable. I will make the remaining PRs roughly the same size. This PR merged 148/599 changed lines (additions/deletions), so we have merged 1 out of 4 PRs need for supporting ABCs and Enums. 🎉

This is sizable progress. @mmckerns, hope that this plan isn't too cumbersome.

**Comment by mmckerns** [comment]
note does not seem to close #250

**Pull request merged**
