### PR TITLE
Optimize the numpy hook

### PR DESCRIPTION
**Pull request by leogama**
As this is now called from `Pickler.save()`, which can be called from a dozen to thousands of times for a single "dump":
- Moved repeated logic to outside the numpy test functions
- Only create a save function once for each type
- Remove logic related to Python 2 old style classes
- Substituted black magic like comparing `id(obj1.__bound_method__) == id(obj2.__bound_method__)`* by  `type(obj1).__unbound_method__ is type(obj2).__unbound_method__)`

(*) I was surprised that it worked at all, must be some kind of optimization but this is not described in the language.

Amend to #540

### CODE REVIEW

**Comment by leogama** [comment]
@mmckerns: The tests are failing because `CLibraryLoaderType` (`ctypes.cdll` of type `ctypes.LibraryLoader`) is registered as unpickleable for CPython < 3.11b3, but it pickles just fine. This class has `__reduce__()` and `__reduce_ex__()` methods implemented.

https://github.com/uqfoundation/dill/blob/bf0f4fa48358fac0a9246a3f12575767d1d14b6f/dill/_objects.py#L191-L193

**Comment by mmckerns** [comment]
Obviously, the types should just be registered the once, so yeah checking if they are in the dispatch table is the right thing to do.  Thanks for the PR.

**Comment by mmckerns** [comment]
> The tests are failing because CLibraryLoaderType (ctypes.cdll of type ctypes.LibraryLoader) is registered as unpickleable

It was failing due to `getattr(cdll, 'mro', int.mro)` throwing a `OSError` in the `numpy*` check functions. Fixed in: 43fd2ca082448e545ca98a4ba72327a0912e7672

**Comment by leogama** [comment]
> It was failing due to `getattr(cdll, 'mro', int.mro)` throwing a `OSError` in the `numpy*` check functions.

This doesn't make sense... The old versions of the `numpy*` functions were effectively calling `getattr(cdll.__class__, 'mro', int.mro)` (on the `cdll` class, not on the object). Furthermore, the lines that were generating the error are removed in this PR. So if the supposed failure to pickle `cdll` has anything to do with that functions, just the adjustment to `_objects.py` should be enough to solve the test error.

**Comment by mmckerns** [comment]
> Note: on my machine, with all Python versions, cdll pickles just fine, so I can't track down this issue.

I have VMs for all supported platforms. The `OSError` didn't occur on linux, but did otherwise... so, yes, once that was adjusted for, then `cdll` pickled... and adjusting `_objects.py` enables the tests to pass.

**Review by mmckerns — APPROVED** [review]

**Pull request merged**
