### PR TITLE
Fix dill.source.getsource compatibility for IPython interactive session.

### PR DESCRIPTION
**Pull request by VincentDary**
Come back of the https://github.com/uqfoundation/dill/pull/464, sorry I didn't think you would be interested.

### CODE REVIEW

**Comment by mmckerns** [comment]
I'm very interested.

**Comment by VincentDary** [comment]
Ok, I'm no familiar with `jupyter` but I will check this compatibility issue.

**Comment by mmckerns** [comment]
>  Standard Library inspect.getsource() actually works on IPython and Jupyter

Interesting. I just tested this... and can confirm it does
```
Python 3.7.13 (default, May 10 2022, 11:13:40) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import inspect

In [2]: def foo(x):
   ...:     return x*foo(x)
   ...: 

In [3]: inspect.getsource(foo)
Out[3]: 'def foo(x):\n    return x*foo(x)\n'

```

That's good, as it didn't used to work. You'd get results like you get from a python shell:
```
>>> import inspect
>>> 
>>> def foo(x):
...   return x*x*x
... 
>>> inspect.getsource(foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 973, in getsource
    lines, lnum = getsourcelines(object)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

```
> Why is it better to get the source file from the object's module instead of the object directly like inspect.findsource() does? Looking at the inspect.getfile() code it appears that the heuristics used there won't work for all types of objects, but shouldn't getting the file through the module be just a fallback method? If yes, then changing this could make inspection work out of the box for IPython and Jupyter, with no need to mess around with the history there.

It's my understanding that `getsource` uses `getsourcelines` which uses `findsource`, where `findsource` retrieves the module's code and the linenumber of where the code starts.  Some of the code from `dill.souce` is very similar to what is in `inspect`.

So, we should trace down why this happens, and see to what depth in the code we can leverage what `inspect` is doing without losing functionality in `dill.source`.

**Comment by leogama** [comment]
> It's my understanding that `getsource` uses `getsourcelines` which uses `findsource`, where `findsource` retrieves the module's code and the linenumber of where the code starts. Some of the code from `dill.source` is very similar to what is in `inspect`.

That's exactly what I've found. However, `inspect` gets the source file directly from the object, while `dill.source` first tries to get the object's module and then the module's file. I guess that generally the module's file and the object's file (retrieved from `func.__code__.co_filename` in the case of functions) are the same, but in this special case they are not:

```python
In [1]: import inspect, __main__
In [2]: def f(): pass
In [3]: f.__module__ 
Out[3]: '__main__'
In [4]: inspect.getfile(f)
Out[4]: '<ipython-input-2-40d3b0035d30>'
In [5]: inspect.getfile(__main__)
---------------------------------------------------------------------------
(...)
TypeError: <module '__main__'> is a built-in module
```

The question is: why does `dill.source` diverges from `inspect` and tries to retrieve the source file from the object's module? Is it because it covers more types of objects? And, more important, is it safe to use this strategy just as a fallback, or would it break some other corner case?

**Comment by mmckerns** [comment]
I'm closing this, as there's a duplicate PR (#531) that also appears to work in `jupyter`.

**Pull request closed without merging**
