### PR TITLE
Drop support for EOL Python

### PR DESCRIPTION
**Pull request by hugovk**
For #260.

In general, supporting and testing EOL versions is becoming increasingly difficult as other packages and tools drop them. 

EOL Pythons (<=2.6, 3.0-3.3) no longer receive security updates, or any updates, from the core Python team. It is possible to upgrade Python on Linux to a supported version for those who care about security. Those who don't can pin to an older version.

Dropping old ones, particularly Python 2.6 (which has been EOL for over 4 years) and 3.2 (2 years), allows code to be updated to use more modern features of Python.

https://en.wikipedia.org/wiki/CPython#Version_history

Also, EOL versions are also little used.

Here's the pip installs for dill from PyPI for last month:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  70.53% |        223,761 |
| 3.6            |  15.89% |         50,408 |
| 3.5            |   7.16% |         22,715 |
| 3.4            |   6.36% |         20,171 |
| 2.6            |   0.03% |             84 |
| 3.7            |   0.02% |             66 |
| 3.3            |   0.01% |             43 |
| None           |   0.00% |              5 |
| 3.2            |   0.00% |              1 |

Source: `pypinfo --start-date -60 --end-date -30 --percent --pip --markdown dill pyversion`

### CODE REVIEW

**Comment by hugovk** [comment]
Rebased to fix conflicts.

---

Here's pip installs June 2018, EOL numbers dropping from 128 to 19:

| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  60.75% |        181,075 |
| 3.6            |  25.08% |         74,754 |
| 3.5            |   8.21% |         24,461 |
| 3.4            |   5.92% |         17,634 |
| 3.7            |   0.04% |            127 |
| 2.6            |   0.00% |             10 |
| 3.3            |   0.00% |              7 |
| 3.2            |   0.00% |              2 |
| Total          |         |        298,070 |

Source: `pypinfo --start-date 2018-06-01 --end-date 2018-06-30 --percent --markdown dill pyversion`

**Comment by hugovk** [comment]
Thanks for the update, that makes perfect sense.

In the meantime, I've created https://github.com/uqfoundation/dill/pull/282, as a couple of the things would be useful in any case.

**Comment by hugovk** [comment]
(Rebased to resolve conflict.)

**Comment by hugovk** [comment]
(Merged to resolve conflicts.)

**Comment by mmckerns** [comment]
As I'm sure you know, there's a push to drop support for old versions of python. I'll try to phase out old versions in stages this year, based on stats like those you've posted.  A new release of `dill` is just around the corner, and will probably as a first step, just narrow the supported versions in setup.py.

**Comment by hugovk** [comment]
Sounds good, here's stats for April 2020:

| category | percent | downloads |
|----------|--------:|----------:|
| 3.7      |  36.83% | 2,068,595 |
| 3.6      |  32.83% | 1,843,934 |
| 2.7      |  22.16% | 1,244,565 |
| 3.5      |   6.92% |   388,418 |
| 3.8      |   1.08% |    60,387 |
| null     |   0.14% |     7,979 |
| 3.4      |   0.04% |     2,073 |
| 3.9      |   0.00% |        93 |
| 2.6      |   0.00% |        15 |
| 3.2      |   0.00% |         1 |
| 3.3      |   0.00% |         1 |
| Total    |         | 5,616,061 |

Source: `pip install -U pypistats && pypistats python_minor dill --last-month`

**Comment by mmckerns** [comment]
First stage of this in: https://github.com/uqfoundation/dill/commit/19d24fa9c514dccf71e5c5fd33d6c691388b9e0d, abort setup for older versions

**Pull request closed without merging**
