### PR TITLE
use with statement instead of try...finally

### PR DESCRIPTION
**Pull request by stegben**
Kind of a PEP8 issue. It's easier to read.

### CODE REVIEW

**Comment by matsjoyce** [comment]
The reason it is not used is that python 2.5 may not have it, and that is a currently supported version of python for dill. If you want to use that, you need `from __future__ import with_statement`.

**Comment by stegben** [comment]
Got it.

**Comment by mmckerns** [comment]
regardless, thanks for submitting the PR

**Comment by matsjoyce** [comment]
We can merge it if and when we drop 2.5 :grin:

**Comment by mmckerns** [comment]
@matsjoyce: absolutely

**Comment by stegben** [comment]
@mmckerns You're welcome. `dill` is a really useful package.

**Pull request closed without merging**
