### PR TITLE
Support ABC and Enums

### LINKED ISSUE #250: "maximum recursion depth exceeded " when serializing enum in python2.7
After `pip2.7 install enum34 dill` running the following script with python2.7

```
import dill
import enum

class SomeEnumType(enum.Enum):
  VALUE_A = "value_a"
  VALUE_B = "value_b"
dill.dumps(SomeEnumType.VALUE_A)
```

fails with
RuntimeError: maximum recursion depth exceeded while calling a Python object

the same script under python3 works fine.

### LINKED ISSUE #332: TypeError: can't pickle _abc_data objects
On Python 3.7, I'm getting this error:

```
Traceback (most recent call last):
  File "../scripts/make_preprocessor.py", line 101, in <module>
    pickle.dump(preprocessor, f)
  File "/home/ubuntu/repo/.venv/lib/python3.7/site-packages/dill/_dill.py", line 287, in dump
    pik.dump(obj)
  File "/usr/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/repo/.venv/lib/python3.7/site-packages/dill/_dill.py", line 910, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 816, in save_list
    self._batch_appends(obj)
  File "/usr/lib/python3.7/pickle.py", line 840, in _batch_appends
    save(x)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 771, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python3.7/pickle.py", line 633, in save_reduce
    save(cls)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/repo/.venv/lib/python3.7/site-packages/dill/_dill.py", line 1323, in save_type
    obj.__bases__, _dict), obj=obj)
  File "/usr/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 786, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/ubuntu/repo/.venv/lib/python3.7/site-packages/dill/_dill.py", line 910, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.7/pickle.py", line 856, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 882, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle _abc_data objects
```

I believe it may be related to this issue: https://github.com/cloudpipe/cloudpickle/issues/180

### LINKED ISSUE #365: Dill can't pickle abstractproperty, abstractclassmethod, or abstractstaticmethod objects
The following:
```python
import abc
import dill

print(dill.__version__)  # 0.3.1.1

class FooBar(abc.ABC):

    @abc.abstractproperty
    def thingy(self):
        return 42


dill.dumps(FooBar)
```
fails with:
```
---------------------------------------------------------------------------                                                                                                                                         
TypeError                                 Traceback (most recent call last)                                                                                                                                         
<ipython-input-4-ad16237f3136> in <module>                                                                                                                                                                          
----> 1 dill.dumps(FooBar)                                                                                                                                                                                          
                                                                                                                                                                                                                    
~/.venvs/dill/lib/python3.7/site-packages/dill/_dill.py in dumps(obj, protocol, byref, fmode, recurse, **kwds)                                                                                                      
    263     """pickle an object to a string"""                                                                                                                                                                      
    264     file = StringIO()                                                                                                                                                                                       
--> 265     dump(obj, file, protocol, byref, fmode, recurse, **kwds)#, strictio)                                                                                                                                    
    266     return file.getvalue()                                                                                                                                                                                  
    267                                                                                                                                                                                                             
                                                                                                                                                                                                                    
~/.venvs/dill/lib/python3.7/site-packages/dill/_dill.py in dump(obj, file, protocol, byref, fmode, recurse, **kwds)                                                                                                 
    257     _kwds = kwds.copy()                                                                                                                                                                                     
    258     _kwds.update(dict(byref=byref, fmode=fmode, recurse=recurse))                                                                                                                                           
--> 259     Pickler(file, protocol, **_kwds).dump(obj)                                                                                                                                                              
    260     return                                                                                                                                                                                                  
    261                                                                                                                                                                                                             
                                                                                                                                                                                                                    
~/.venvs/dill/lib/python3.7/site-packages/dill/_dill.py in dump(self, obj)                                                                                                                                          
    443             raise PicklingError(msg)                                                                                                                                                                        
    444         else:                                                                                                                                                                                               
--> 445             StockPickler.dump(self, obj)                                                                                                                                                                    
    446         stack.clear()  # clear record of 'recursion-sensitive' pickled objects                                                                                                                              
    447         return                                                                                                                                                                                              
                                                                                                                                                                                                                    
/usr/lib/python3.7/pickle.py in dump(self, obj)                                                                                                                                                                     
    435         if self.proto >= 4:                                                                                                                                                                                 
    436             self.framer.start_framing()                                                                                                                                                                     
--> 437         self.save(obj)                                                                                                                                                                                      
    438         self.write(STOP)                                                                                                                                                                                    
    439         self.framer.end_framing()                                                                                                                                                                           
                                                                                                                                                                                                                    
/usr/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)                                                                                                                                                 
    502         f = self.dispatch.get(t)                                                                                                                                                                            
    503         if f is not None:                                                                                                                                                                                   
--> 504             f(self, obj) # Call unbound method with explicit self                                                                                                                                           
    505             return                                                                                                                                                                                          
    506                                                                                                                                                                                                             
                                                                                                                                                                                                                    
~/.venvs/dill/lib/python3.7/site-packages/dill/_dill.py in save_type(pickler, obj)                                                                                                                                  
   1339             del _dict[name]                                                                                                                                                                                 
   1340         pickler.save_reduce(_create_type, (type(obj), obj.__name__,
-> 1341                                            obj.__bases__, _dict), obj=obj)
   1342         log.info("# %s" % _t)
   1343     # special cases: NoneType

/usr/lib/python3.7/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    636         else:
    637             save(func)
--> 638             save(args)
    639             write(REDUCE)
    640 

/usr/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/usr/lib/python3.7/pickle.py in save_tuple(self, obj)
    787         write(MARK)
    788         for element in obj:
--> 789             save(element)
    790 
    791         if id(obj) in memo:

/usr/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

~/.venvs/dill/lib/python3.7/site-packages/dill/_dill.py in save_module_dict(pickler, obj)
    910             # we only care about session the first pass thru
    911             pickler._session = False
--> 912         StockPickler.save_dict(pickler, obj)
    913         log.info("# D2")
    914     return

/usr/lib/python3.7/pickle.py in save_dict(self, obj)
    857 
    858         self.memoize(obj)
--> 859         self._batch_setitems(obj.items())
    860 
    861     dispatch[dict] = save_dict

/usr/lib/python3.7/pickle.py in _batch_setitems(self, items)
    883                 for k, v in tmp:
    884                     save(k)
--> 885                     save(v)
    886                 write(SETITEMS)
    887             elif n:

/usr/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    522             reduce = getattr(obj, "__reduce_ex__", None)
    523             if reduce is not None:
--> 524                 rv = reduce(self.proto)
    525             else:
    526                 reduce = getattr(obj, "__reduce__", None)

TypeError: can't pickle abstractproperty objects
```
`abstractclassmethod` and `abstractstaticmethod` also fail in the same way.

### PR DESCRIPTION
**Pull request by anivegesana**
1) Support ABC classes (supersedes #427)
2) Support Enum classes
3) Replace `_dict_from_dictproxy` with cloudpickle equivalent that doesn't save the members of the parent classes

Fixes #250, fixes #332, fixes #365

### CODE REVIEW

**Comment by gabyx** [comment]
Any progress on this?

**Comment by anivegesana** [comment]
For most cases, the PR as it is works. But for a couple of edge cases (like ABC classes that redefine `__new__` or `__prepare__`) some work needs to be done. I can guarantee that any class that is successfully pickled on this PR will continue to work when I fix those edge cases (and will likely still unpickle on master, but I didn't verify this), so if you need the feature urgently, you can pin dill to this commit and use it, but I do not guarantee that it will work for all ABCs. If you find out your ABC doesn't work, it will help me debug and it would be much appreciated.

**Comment by anivegesana** [comment]
@mmckerns Since demand is high, do you think that we should pull this PR (since it works in most cases) and open another PR where I tackle the remaining cases, so that people can use this feature in dill 0.3.5?

**Comment by mmckerns** [comment]
I am updating the way `dill` builds and installs, and not taking any new features for 0.3.5.  The release is done, and just needs testing.  I expect it to drop tomorrow.  So, short answer, no, not for 0.3.5.

**Comment by mmckerns** [comment]
Also, I'd rather not make mistakes and then have to backtrack and break things backward.  It's better to be careful and a bit slow.

**Comment by anivegesana** [comment]
In the process of trying to detect when it broke, I was able to find the bug. Now, the only case that I am aware of that this PR isn't working on is date enums.

**Comment by anivegesana** [comment]
@mmckerns I have reason to believe that, on the master branch, `__new__` is broken for all classes, not just ABCs. I think we don't have any test cases that concern `__new__`, so I didn't catch it earlier. These few lines fix it: https://github.com/uqfoundation/dill/pull/450/files#diff-bdd40cc870892c410adce8c1b155daf5e6c5b5e7192e751f171e6dae6a578dc1R1622-R1628

If you aren't done making the release, can we add that to the release? Although it is not that common, I am sure that someone will pickle a class with `__new__` in it and will cause an error. Tested it on `mystic/examples3/test_lub_expected_error1.py` and it doesn't break the other inner function test case.

**Comment by mmckerns** [comment]
> These few lines fix it: https://github.com/uqfoundation/dill/pull/450/files#diff-bdd40cc870892c410adce8c1b155daf5e6c5b5e7192e751f171e6dae6a578dc1R1622-R1628

I'm done with changes and most of the testing, and will cut a PR to update the build before cutting the release.  I haven't done the release yet, and may not until tomorrow.  Go ahead and put the change into a PR, and I'll look at it. I can likely pull it before the release.

**Comment by anivegesana** [comment]
@mmckerns Not urgent. There is no way to pickle enums that look like this without additional information:
```py
class AutoNumber(IntEnum):
    def __new__(cls):
        value = len(cls.__members__) + 1
        obj = int.__new__(cls, value)
        obj._value_ = value
        return obj

class Color(AutoNumber):
    red = ()
    green = ()
    blue = ()
```

The values assigned to the class attributes get updated with the enum value itself, so it is impossible to recover the constructor arguments. Should there be a hook or register function to define this new form of reduction, or should we just leave this feature as unsupported. cloudpickle doesn't support this either, but it generates the error during unpickling, which I find undesirable.

**Comment by anivegesana** [comment]
Thoughts about making this part of the API public so that others can register hooks for pickling custom metaclasses that are not supported by this PR, like Django models: https://github.com/uqfoundation/dill/pull/450/files#diff-bdd40cc870892c410adce8c1b155daf5e6c5b5e7192e751f171e6dae6a578dc1R1962-R1966

**Comment by anivegesana** [comment]
@mmckerns I don't think we can get this PR in by dill 0.3.6 because of how big it is (I am sorry, I promised no more big ones, but this one is not that easy to break up into smaller pieces and still function,) but can we start a review on it so it doesn't become stale?

**Comment by mmckerns** [comment]
Sure, just let me know which PRs are ready to be reviewed.  I'll tag this one.

**Comment by anivegesana** [comment]
Is this PR being reviewed?

**Comment by mmckerns** [comment]
@anivegesana: not yet.  I prioritized the PRs marked for 0.3.6, and I haven't had time to fit it in aside from that. Can you clarify, do you feel the PR is "finished", aside from what comes up in the review?  That will help me determine how to prioritize it.

**Comment by anivegesana** [comment]
I guess this PR has been "finished" for a while. The problem is that this PR tackles ABCs and Enums in the same PR because without a definite plan on how to incorporate both of them, it would have been hard to support both. But now, other PRs are leading to lots of merge conflicts and it might be better off to close this PR and reopen many smaller PRs that address smaller incomplete subsets of ABCs and Enums. It would help avoid bugs like #486 because it would be easier to merge individual pieces independent of others and not cause problems. If you haven't looked at this PR yet, that is the route I will take rather than creating another merge commit.

**Comment by leogama** [comment]
Do you want me to try to manually merge this PR with master?

**Comment by anivegesana** [comment]
Sure. You can give it a shot.

**Comment by leogama** [comment]
It think I succeeded with the 3-way manual merge. It was easier than I thought. Opened a [PR to your fork](https://github.com/anivegesana/dill/pull/1).

**Comment by anivegesana** [comment]
There were many problems with this PR due to its size. It began to become too hefty and difficult to keep up with master to the point that I just gave up. Because this feature was demanded by many people, they started fork this branch and stop updating dill in order to pickle ABCs and enums. This means that I probably should keep backwards compatibility with older commits on this branch, to prevent people from getting upset. New additions to the `enum` module in Python 3.11 make everything much more complicated. And it seems like other people who want to contribute fixes in order to add the functionality to master are blocked because they would be blocked by this unmaintainable monster.

Here is my plan. I will not keep this branch up to date with master. I will update it to work with Python 3.11 enums, while still supporting pickles from older versions of this branch. I can then ask how is this PR generally speaking (not a full review, just a general idea of if it is readable and is likely to be approved later). Then, I will break it up into smaller pieces for final approval.

@mmckerns Does this seem like a good plan? This will require a large amount of work and I probably won't be able to put any significant dent in it until the summer. I believe that this is a more important task than #534, so I will look into this instead.

**Comment by mmckerns** [comment]
@anivegesana (this also a good note for @leogama): I've been hired in the past essentially to merge large unwieldy PRs. It can be a nasty task. Your instinct is correct in that small (the smaller the better) PRs are easy to merge.  However, I strongly suggest you only pull off one or two small PRs at a time.  Essentially, you want them as small as possible... and you want to also (1) propagate the changes back into this PR, and (2) not have too many small open PRs as it will become a management nightmare as each small PR has some small changes to it before it is merged.  What you want ultimately is to get this PR to merge, incrementally through small PRs moving it closer to master.  It will take time, so don't be in a rush.  If you are most interested in this feature, then go for it.

**Comment by anivegesana** [comment]
I am thinking about breaking it into 3-4 pieces: "special metaclass framework utilities" that will allow for the customization of how metaclasses are pickled, ABCs, enums, and 3.11 enums (if new changes are significant). Let me know if a different breakdown is preferable.

**Comment by mmckerns** [comment]
"special metaclass framework utilities": this is a good place to start... and to do in one or more PRs.

**Pull request closed without merging**
